# Generated by Django 3.2.9 on 2021-11-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Not Specified', 'Not Specified'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Not Specified', max_length=15, verbose_name='Gender'),
        ),
    ]
